name: Elixir CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  MIX_ENV: test
  
jobs:
  build:
    runs-on: ubuntu-latest
    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    strategy:
      matrix:
        otp: ['23.3', '24.0']
        elixir: ['1.12.1', '1.11.4']
    steps:
    - uses: actions/checkout@v2
    - uses: erlef/setup-beam@v1
      with:
        otp-version: ${{matrix.otp}}
        elixir-version: ${{matrix.elixir}}
    - name: Install dependencies
      run: mix deps.get
    - name: Run linter
      run: mix credo --strict
    - name: Run tests
      run: mix test
    - name: Run dialyzer
      run: mix dialyzer